name: CI

on:
  push:
    branches:
      - main
      - "renovate/*" # Adjust this based on your branch strategy
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies
        run: npm install

  test_and_publish:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install npm
        run: npm install -g npm@9.8.1

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - run: git config --global user.email "bhiri22@gmail.com"
      - run: git config --global user.name "hellcat29a"

      - name: Stash git changes
        run: git stash || echo "No changes to stash"

      - name: Run Lerna
        run: npm run lerna:all
