name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set npm Global Directory
        run: |
          mkdir -p ~/.npm-global
          npm config set prefix '~/.npm-global'
          echo 'export PATH=$HOME/.npm-global/bin:$PATH' >> $GITHUB_ENV

      - name: Install npm
        run: npm install -g npm@9.8.1

      - name: Install Dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm install

      - name: Build
        run: npm run build

      - name: Publish Packages
        run: npm run lerna:all
