name: Publish
on:
  push:
    branches:
      - main
      - "renovate/*" # Adjust this based on your branch strategy
  pull_request:
    branches:
      - main
jobs:
  publish:
    name: Publish NPM Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "bhiri22@gmail.com"
      - run: git config --global user.name "hellcat29a"
      - name: Create ~/.npmrc file
        run: |
          echo "//registry.npmjs.org/:_authToken=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" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: 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
