name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm install

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hellcat29A/test-with-registry.git

      - name: Commit Changes
        run: |
          git add package-lock.json .turbo/
          git commit -m "Update package-lock.json and .turbo directory" || echo "No changes to commit"

      - name: Build
        run: npm run build

      - name: Publish Packages
        run: npm run lerna:all
