name: Publish
on:
  push:
    branches:
      - main
      - "renovate/*" # Adjust this based on your branch strategy
  pull_request:
    branches:
      - main
jobs:
  publish:
    name: Publish NPM Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install --f

      - name: Build Project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"

      - name: Create ~/.npmrc file
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc

      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/hellcat29A/test-with-registry.git

      - name: Run Lerna
        run: npm run lerna:all
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
